### ISSUE TITLE
Test User

### ISSUE THREAD

**Issue by satishnath** [jwoods1/xpress#1]
Thanks for sharing the project. I am exploring the app and was wondering if there was test account that i can use.

Thanks!!

**Comment by jwoods1** [comment]
I created this for a school project.  Here are the some dummy users.
ADMIN: 
FSU-Admin
Winter2017

DEV: 
FSU-DEV
Winter2017

CLIENT:
FSU-CLIENT
Winter2017

**Comment by satishnath** [comment]
Thanks again!!
